import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def get_judgement(json_input, observation_text):
    """
    json_input: The raw JSON dictionary containing your policies.
    observation_text: The description generated by your Agent A (Inspector).
    """
    
    # 1. Format the policies into a readable string list
    try:
        policy_text = "\n".join([f"- {p['rule']}: {p['description']}" for p in json_input.get('policies', [])])
    except Exception as e:
        print(f"Error parsing policies: {e}")
        policy_text = "No policies provided."

    # 2. Build the dynamic prompt using f-strings
    prompt = f"""
    SYSTEM: You are the Senior Kitchen Health Inspector. Your job is to evaluate an observation against strict policies.
    
    KITCHEN POLICIES:
    {policy_text}
    
    EVIDENCE (Observation):
    {observation_text}
    
    TASK:
    1. Compare the Evidence to the Policies.
    2. If a policy is violated, state which one.
    3. Assign a Verdict: [PASS, WARNING, VIOLATION].
    4. If the evidence says 'No activity', reply [PASS] - No staff present.
    5. You are strict and only reply with the verdict and the violated policy if any. Do not provide any explanations or additional text.
    """

    # 3. Send the formatted prompt to Groq
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt # Inject the combined prompt here
                        },
                    ],
                }
            ],
            model=os.getenv("UNIFIED_JUDGE_MODEL"), # Best text model , "llama-3.3-70b-versatile"
        )
        return chat_completion.choices[0].message.content
    except Exception as e:
        print(f"Groq Error: {e}")
        return "Error"